export const ERROR_CODES = {
  // Authentication errors
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",

  // Validation errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_INPUT: "INVALID_INPUT",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",

  // Resource errors
  NOT_FOUND: "NOT_FOUND",
  ALREADY_EXISTS: "ALREADY_EXISTS",

  // Database errors
  DATABASE_ERROR: "DATABASE_ERROR",
  QUERY_FAILED: "QUERY_FAILED",
  CONSTRAINT_VIOLATION: "CONSTRAINT_VIOLATION",

  // Service errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  TIMEOUT: "TIMEOUT",

  // Distributed transaction errors
  AUDIT_LOG_FAILED: "AUDIT_LOG_FAILED",
  TRANSACTION_ROLLBACK_FAILED: "TRANSACTION_ROLLBACK_FAILED",
  DISTRIBUTED_TRANSACTION_FAILED: "DISTRIBUTED_TRANSACTION_FAILED",
} as const;
